apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig

metadata:
  name: mi-cluster
  region: us-east-1

managedNodeGroups:
  - name: group-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true # Activar acceso via ssh
    iam: # Esto se tendria que hacer a mano en la configuracion manual
      withAddonPolicies:
        autoScaler: true