# defaultAirflowTag: "2.5.1"
# airflowVersion: "2.5.1"
global:
  defaultStorageClass: "gp2"
auth:
  fernetKey: "BfRwv6uOg9Nr3uVdL2jeR60nV2frcWPQyy5yXzx0YBM="
  # fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
env:
  - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
    value: "False"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
    value: "dev"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
    value: "apache/airflow"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
    value: "slim-2.5.1-python3.8"
executor: "KubernetesExecutor"
rbac:
  create: true
serviceAccount:
  create: true
  automountServiceAccountToken: true
redis:
  enabled: false
scheduler:
  automountServiceAccountToken: true
web:
  automountServiceAccountToken: true
# worker:
#   automountServiceAccountToken: true
## Leera los dags de un repo
dags:
  enabled: True
  repositories:
    - repository: https://github.com/cesar169100/fundamentos_airflow.git
      branch: main
      name: fundamentos-airflow
      path: /dags