defaultAirflowTag: "2.5.1"
airflowVersion: "2.5.1"
# Es una clave criptográfica utilizada para cifrar datos sensibles en Airflow, como conexiones
# o variables. Es fundamental para la seguridad de la instalación.
fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
env:
  - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
    value: "False"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
    value: "dev"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
    value: "apache/airflow"
  - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
    value: "slim-2.5.1-python3.8"
executor: "KubernetesExecutor"
# Lineas no necesarias si la instalacion no es con flux
# createUserJob:
#   useHelmHooks: false
# migrateDatabaseJob:
#   useHelmHooks: false
